# This docker-compose file extends the basic `docker-compose-api.yml`
# with settings relevant for production deployment on a single server.
# For more information see: https://docs.docker.com/compose/extends/
# To test production setup: docker-compose -f docker-compose-api.yml -f docker-compose.prod.yml up
version: '3.7'

services:
  api:
    volumes:
      - api-backend:/backend

  client:
    volumes:
      - client-frontend:/frontend/build

volumes:
  client-node-modules:
  client-frontend:
  api-backend: