# THIS DOCKER-COMPOSE FILE EXTENDS THE BASE `docker-compose.yml`
# WITH SETTINGS RELEVANT FOR PRODUCTION DEPLOYMENT ON A SINGLE
# SERVER. FOR MORE INFORMATION SEE:
# https://docs.docker.com/compose/extends/
version: '3.7'

services:
  models:
    env_file:
      - prod.env

  api:
    env_file:
      - prod.env
    volumes:
      - api-backend:/backend

  client:
    env_file:
      - prod.env
    volumes:
      - client-frontend:/frontend/build

volumes:
  client-node-modules:
  client-frontend:
  api-backend: