version: '3.7'

services:
  models:
    env_file:
      - prod.env
    ports:
      - "80:${MLFLOW_PORT}"

  api:
    env_file:
      - prod.env
    ports:
      - "80:${API_PORT}"
    depends_on:
      - models

  client:
    env_file:
      - prod.env
    ports:
      - '80:${UI_PORT}'
    depends_on:
      - api
